name: chemistry-environment
channels:
  - conda-forge
  - rdkit
  - schrodinger
  - gabrielelanaro
  - moldesign
dependencies:
  - python
  - numpy
  - pymol
  - rdkit
  - chemview
  - pip:
    - RISE
    - jupyter-wysiwyg
    - ipywidgets~=7.0.0b1
    - nglview
    - ipymol
    - mathchem
    - mogli
    - moldesign 